# Generated by Django 4.2.4 on 2023-09-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
